In [1]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('GAORecommendations - TRUE.csv')
df.hea

                   Topic   Department  Count     Agency
0  Government Operations  Agriculture      1  executive
1  Government Operations     Commerce     17  executive
2  Government Operations      Defense     14  executive
3  Government Operations    Education      1  executive
4  Government Operations       Energy      3  executive

In [10]:
df_cyber = df[df['Topic'] == 'Cybersecurity']
df_cyber.shape

(19, 4)

In [11]:
df_cyber.sort_values(by='Count', ascending=False)

            Topic                       Department  Count       Agency
21  Cybersecurity                          Defense     12    executive
29  Cybersecurity                             NASA      8    executive
31  Cybersecurity             Personnel Management      8    executive
36  Cybersecurity                         Treasury      6    executive
24  Cybersecurity                              EPA      6    executive
32  Cybersecurity                        President      5    executive
28  Cybersecurity                          Justice      3    executive
35  Cybersecurity                   Transportation      3    executive
33  Cybersecurity                   Small Business      3  Independent
27  Cybersecurity                              HUD      3    executive
37  Cybersecurity                               VA      2    executive
20  Cybersecurity                         Commerce      2    executive
30  Cybersecurity                          Nuclear      1    executive
26  Cybersecurity                              HHS      1    executive
25  Cybersecurity  General Services Administration      1    executive
34  Cybersecurity                            State      1    executive
23  Cybersecurity                           Energy      1    executive
22  Cybersecurity                        Education      1    executive
19  Cybersecurity                      Agriculture      1    executive

In [12]:
## 68 priority items are cybersecurity

In [13]:
df_gov = df[df['Topic'] == 'Government Operations']
df_gov.shape

(19, 4)

In [14]:
df_gov.sort_values(by='Count', ascending=False)

                    Topic                       Department  Count       Agency
13  Government Operations                        President     20    executive
1   Government Operations                         Commerce     17    executive
2   Government Operations                          Defense     14    executive
12  Government Operations             Personnel Management     10    executive
8   Government Operations                          Justice      9    executive
16  Government Operations                            State      9    executive
5   Government Operations  General Services Administration      7    executive
14  Government Operations                   Small Business      6  Independent
6   Government Operations                              HHS      6    executive
9   Government Operations                             NASA      5    executive
17  Government Operations                         Treasury      3    executive
4   Government Operations                           Energy      3    executive
7   Government Operations                         Interior      2    executive
15  Government Operations                 Social Security       2  Independent
0   Government Operations                      Agriculture      1    executive
11  Government Operations                          Nuclear      1    executive
10  Government Operations      National Science Foundation      1    executive
3   Government Operations                        Education      1    executive
18  Government Operations                               VA      1    executive